project:
  type: website

website:
  title: "Gerardo Rocha Benigno"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Projects"
        href: proyectos.qmd
      - text: "Notes"
        href: notes/index.qmd

format:
  html:
    theme: cosmo
    toc: true
